version: '3'

services:
  api:
    image: node:20
    container_name: api
    working_dir: /app
    command: node server.js
    ports:
      - "3000:3000"
    volumes:
      - "./backend:/app"

  web:
    image: node:20
    container_name: web
    working_dir: /src
    command: npm start
    ports:
      - "3001:3001"
    volumes:
      - "./frontend:/src"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - 'db-data:/data/db'

volumes:
  db-data:
