version: '3'
services:
  api:
    image: node:20
    container_name: api_backend
    working_dir: /app
    command: node server.js
    ports:
      - "3000:3000"
    volumes:
      - "./backend:/backend" 

  web:
    image: node:20
    container_name: api_frontend
    working_dir: /src
    command: npm start
    ports:
      - "3001:3001"
    volumes:
      - "./frontend:/src"  
